### ISSUE TITLE
[Feature request] stream video directly

### ISSUE THREAD

**Issue by mtdvlpr** [semkeijsper/jw-cast#1]
Hi, awesome work! I just found your application and it's really nice. I made something similar (albeit way simpler) myself to fill the need of watching English JW videos with Dutch subtitles. You can find it at https://github.com/mtdvlpr/subtitle-extractor. The only feature I'm missing here that I have implemented is watching the video with subtitles directly from your website. Would you be alright with me forking your repo, altering it to my needs and hosting it?

**Comment by semkeijsper** [comment]
hey Manoah! toch ff in het nederlands, is iets makkelijker :)

je site werkt erg goed! ik wilde die functionaliteit ook integreren, maar kreeg het niet goed aan de praat op mijn site (vooral bij 720p). als je nog steeds openstaat voor een samenvoeging van onze sites, zou ik dat helemaal top vinden en dan mag je een PR maken. hopelijk kunnen we dan zoals on-site playback maken met subtitles, en dan ook dat het cast-icoontje werkt met subtitles. best of both worlds!

laat maar weten :)

**Comment by semkeijsper** [comment]
je kan me ook bereiken op discord Semx11#0001 als je de details wilt bespreken, misschien wat makkelijker dan via een issue. ben gisteren thuisgekomen van vakantie, vandaar dat ik nu pas antwoord :)
