### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by geimist** [semkeijsper/jw-cast#5]
Hello Sem, 
I'm Stephan from Germany. 
Please excuse me for asking a question that is not directly related to your project.

I would like to build an iOS shortcut with which I can quickly display the video transcription (subtitles). 
Unfortunately, I have not yet been able to derive the API call correctly, as I have absolutely no idea about JS. If I have seen it correctly, it all runs in the file [app.8e57863e.js](https://github.com/semkeijsper/jw-cast/blob/master/dist/js/app.8e57863e.js).

Thank you very much 🤗
Stephan

**Comment by mtdvlpr** [comment]
See [this API call](https://b.jw-cdn.org/apis/mediator/v1/media-items/E/pub-jwbvod24_15_VIDEO?clientType=www) for example.

The subtitles are in `media[0].files[4].subtitles`. In this case:

```js
{
	"subtitles": {
		"url": "https://d34ji3l0qn3w2t.cloudfront.net/68352eb2-e731-42b1-a68c-c7e857885ce3/1/jwbvod24_E_15.vtt",
		"modifiedDatetime": "2023-12-05T18:53:12.000Z",
		"checksum": "9f73e89d508fec93d557d54ec9e9fa39"
	}
}
```

**Comment by semkeijsper** [comment]
Hi Stephen, thanks for reaching out :)

You don't need to understand JavaScript to read the jw.org API responses, you just need to understand JSON. If you are unfamiliar with this, I recommend reading up on that first.

To add onto Manoah, the API call he linked consists of multiple elements:
`https://b.jw-cdn.org/apis/mediator/v1/media-items/<LANGCODE>/<PUBID>?clientType=www`

For English, the LANGCODE would be `E`. For German, it is `X`. You can find all available languages and their langcode using this API call: `https://b.jw-cdn.org/apis/mediator/v1/languages/X/all?clientType=www` (again, change X into E or something else for different languages)

Now the PUBID is the unique ID of the video you want to get information of. The easiest way to find one is by browsing a category, such as 'LatestVideos': `https://b.jw-cdn.org/apis/mediator/v1/categories/X/LatestVideos?detailed=1&clientType=www`. Inside the `media` array, you will find the latest jw.org videos along with their title, files, and most importantly, the `languageAgnosticNaturalKey`, or LANK for short. This is the PUBID you need to put into the request to retrieve subtitle information.

From there, you will get all available video qualities of that video (144p to 720p) inside the `files` array, and any video with a resolution greater than 240p will have the subtitles files (.vtt) attached. From there you can download it, and parse it any way you like.

If you have any other question, feel free to reply :)

PS: you linked app.xxxxx.js, this is a compiled file which is unreadable. If you want to take a look at the source code, it's inside the `src` folder. The logic you are looking for resides in [App.vue](https://github.com/semkeijsper/jw-cast/blob/master/src/App.vue) and [VideoDialog.vue](https://github.com/semkeijsper/jw-cast/blob/master/src/components/VideoDialog.vue).

**Comment by geimist** [comment]
Thank you @semkeijsper and @mtdvlpr for your answers. Yes, I had already tried various things with the API, but had obviously not chosen the correct parameters. Now I've made some progress thanks to you and am working on my shortcut.

> Now the PUBID is the unique ID of the video you want to get information of. The easiest way to find one is by browsing a category, such as 'LatestVideos': `https://b.jw-cdn.org/apis/mediator/v1/categories/X/LatestVideos?detailed=1&clientType=www`

Since I share the URL of the current page or video from the JW Library directly in the shortcut, I already have the desired name (`...pub<xxx>VIDEO...`), which I can successfully pass to the API.
Now it's time for the finishing touches, which, as you know, take the longest.

Thanks again.

**Comment by geimist** [comment]
Hello everyone,

Even if this isn't the perfect place, I don't want to keep the result to myself. It's nothing major, but I find it very practical and have wanted to implement it for a long time.
https://www.icloud.com/shortcuts/17ace694425e45c5bc003f2be7c095c3
[JW subtitle.shortcut.zip](https://github.com/semkeijsper/jw-cast/files/14760996/JW.subtitle.shortcut.zip)

Formatting the VTT file with RegEx in the Shortcuts app almost made me despair. It's not perfect yet, but I think it's usable.

**Usage:**
Videos can be shared in the JW Library or on JW.org with the shortcut. The query works if one of the following parameters is present in the URL: `docid.*VIDEO`, `pub.*VIDEO` or `docid=\d+`.

There is also a query with the desired target language. You can change the language list or hardcode your own language.

Best regards
Stephan

**Comment by semkeijsper** [comment]
@geimist Works great! I just tried it out on my iPhone. I didn't know shortcuts could do so much, I don't use my iPhone often, my main is an Android. I'm impressed!

If you want to see how JWCast formats the .vtt files with regex, [you can see it here](https://github.com/semkeijsper/jw-cast/blob/master/src/components/TranscriptDialog.vue#L101:L105).

Thanks for sharing :)

**Comment by geimist** [comment]
Yes, you can already implement many beautiful things.

> If you want to see how JWCast formats the .vtt files with regex, [you can see it here](https://github.com/semkeijsper/jw-cast/blob/master/src/components/TranscriptDialog.vue#L101:L105).

Many thanks for that. I had really tried several solutions, which worked fine in the shell, but not in shortcuts. For example, the leading spaces of a line are simply not matched (neither with `^\s+` nor with `^[ ]+`). There are also third-party apps that extend the possibilities of shortcuts many times over, but I didn't want the user to have to install an additional application.
